name: run main.py

on:
  schedule:
    - cron: '*/15 * * * *' 

jobs:
  build:
    runs-on: ubuntu-20.04.1
    steps:

      - name: checkout repo content
        uses: actions/checkout@v2 # checkout the repository content to github runner

      - name: setup python
        uses: main@v4
        with:
          python-version: '3.9' # install the python version needed
          
      - name: install python packages
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          
      - name: execute py script # run main.py
        env:
          SOME_SECRET: ${{ secrets.SOME_SECRET }}
        run: python main.py
          
      - name: commit files
        run: |
          git config --local user.email "christianalosant@gmail.com"
          git config --local user.name "Christian Alonso"
          git add -A
          git diff-index --quiet HEAD || (git commit -a -m "updated logs" --allow-empty)
          
      - name: push changes
        uses: ad-m/github-push-action@v0.6.0
        with:
          repository: 'main' # Reemplaza con tu nombre de usuario y nombre del repositorio
          ssh-key: ${{ secrets.SSH_PRIVATE_KEY }}
          fetch-depth: 0
